### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by prithaupadhyay** [prithaupadhyay/CSS-Loaders#6]

**Comment by anabellaspinelli** [comment]
I can do it! 😄

**Comment by prithaupadhyay** [comment]
@anabellaspinelli Go ahead

**Comment by d3vil0p3r** [comment]
@prithaupadhyay checkout #10

**Comment by prithaupadhyay** [comment]
@d3vil0p3r  I am sorry. @anabellaspinelli  submitted the PR first and I find it fine. You can work on other issues.

**Comment by d3vil0p3r** [comment]
@d3vil0p3r sure. Thanks

**Comment by d3vil0p3r** [comment]
@prithaupadhyay sure, thanks 😊
